version: '3.9'

networks:
  my-playground:
    external:
      name: playground


volumes:
  db_data:

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - my-playground
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-playground

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - my-playground
