version: '3.9'

networks:
      playground:
        driver: bridge


volumes:
  db_data:

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - playground
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - playground

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - playground
